"""Provider-abstracted async LLM client with tools, structured output, and fallback."""

from forge.llm.cache import CacheBackend, InMemoryCache, RedisCache, cache_key
from forge.llm.cost import compute_cost
from forge.llm.errors import map_litellm_exception, raise_as_provider_error
from forge.llm.messages import (
    AnyMessage,
    AssistantMessage,
    ContentPart,
    Message,
    Role,
    SystemMessage,
    TextPart,
    ToolCall,
    ToolResultMessage,
    UserMessage,
    validate_conversation,
)
from forge.llm.multimodal import ImageContent, downscale_image
from forge.llm.providers import (
    AnthropicConfig,
    AnthropicProvider,
    AzureConfig,
    AzureProvider,
    BedrockConfig,
    BedrockProvider,
    OpenAICompatConfig,
    OpenAICompatProvider,
    OpenAIConfig,
    OpenAIProvider,
    ProviderClient,
    ProviderConfig,
    VertexConfig,
    VertexProvider,
    to_anthropic_tool_schema,
    to_gemini_tool_schema,
    to_openai_tool_schema,
)
from forge.llm.registry import (
    Capabilities,
    Modality,
    Model,
    Pricing,
    ProviderName,
    ProviderRoute,
    Registry,
    Tier,
    Vendor,
    registry,
)
from forge.llm.responses import (
    FinishReason,
    LLMResponse,
    ResponseChunk,
    ToolCallDelta,
    Usage,
)
from forge.llm.routing import ModelRoute, resolve
from forge.llm.schemas import (
    StructuredOutputError,
    make_reprompt_instruction,
    parse_json_response,
    pydantic_to_json_schema,
    to_anthropic_forced_tool_schema,
    to_gemini_response_schema,
    to_openai_response_format,
)
from forge.llm.streaming import JSONAccumulator, accumulate_text, accumulate_tool_calls
from forge.llm.tokens import count_tokens
from forge.llm.tools import Tool, ToolFunc, ToolLoopExceededError, tool

__all__ = [
    "AnthropicConfig",
    "AnthropicProvider",
    "AnyMessage",
    "AssistantMessage",
    "AzureConfig",
    "AzureProvider",
    "BedrockConfig",
    "BedrockProvider",
    "CacheBackend",
    "Capabilities",
    "ContentPart",
    "FinishReason",
    "ImageContent",
    "InMemoryCache",
    "JSONAccumulator",
    "LLMResponse",
    "Message",
    "Modality",
    "Model",
    "ModelRoute",
    "OpenAICompatConfig",
    "OpenAICompatProvider",
    "OpenAIConfig",
    "OpenAIProvider",
    "Pricing",
    "ProviderClient",
    "ProviderConfig",
    "ProviderName",
    "ProviderRoute",
    "RedisCache",
    "Registry",
    "ResponseChunk",
    "Role",
    "StructuredOutputError",
    "SystemMessage",
    "TextPart",
    "Tier",
    "Tool",
    "ToolCall",
    "ToolCallDelta",
    "ToolFunc",
    "ToolLoopExceededError",
    "ToolResultMessage",
    "Usage",
    "UserMessage",
    "Vendor",
    "VertexConfig",
    "VertexProvider",
    "accumulate_text",
    "accumulate_tool_calls",
    "cache_key",
    "compute_cost",
    "count_tokens",
    "downscale_image",
    "make_reprompt_instruction",
    "map_litellm_exception",
    "parse_json_response",
    "pydantic_to_json_schema",
    "raise_as_provider_error",
    "registry",
    "resolve",
    "to_anthropic_forced_tool_schema",
    "to_anthropic_tool_schema",
    "to_gemini_response_schema",
    "to_gemini_tool_schema",
    "to_openai_response_format",
    "to_openai_tool_schema",
    "tool",
    "validate_conversation",
]
